export const productCategory = [
  "Electronics",
  "Fashion",
  "Beauty and Personal Care",
  "Home and Kitchen Appliances",
  "Furniture and Home Decor",
  "Sports and Fitness Equipment",
  "Books and Stationery",
  "Toys and Games",
  "Health and Wellness",
  "Automotive and Tools",
  "Groceries and Gourmet Food",
  "Jewelry and Accessories",
  "Baby and Maternity Products",
  "Pet Supplies",
  "Office Supplies",
  "Arts and Crafts",
  "Musical Instruments",
  "Movies, Music, and Entertainment",
  "Outdoor and Camping Gear",
  "Travel and Luggage",
  "Industrial and Scientific Equipment",
  "Party Supplies",
  "Garden and Outdoor Living",
  "Watches",
  "Collectibles and Memorabilia",
];
